
name: env-GBM8378
dependencies:
  - pip
  - ffmpeg
  - python=3.6
  - pip:
    - numpy==1.18.2
    - jupyter
    - pydicom==1.4.1
    - nibabel==2.5.1
    - niwidgets==0.2.2
    - matplotlib==3.1.2
    - scikit-image==0.17.2
    - tqdm~=4.56.0
